[General]
showlogo=shown
showClock=true
logo=/usr/share/pixmaps/iulinux-logo.png
type=image
color=#0b0f14
fontSize=10
background=/usr/share/wallpapers/IULinux/contents/images/3840x2160.png
needsFullUserModel=false
