---
modules-search: [ local ]

instances:
  - id: target_cleanup
    module: shellprocess
    config: shellprocess_target_cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary

  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - initramfs
      - grubcfg
      - bootloader
      - shellprocess@target_cleanup
      - umount

  - show:
      - finished

branding: iulinux

prompt-install: true
dont-chroot: false
oem-setup: false

disable-cancel: false
disable-cancel-during-exec: true

hide-back-and-next-during-exec: true
quit-at-end: false
