# IULinux build configuration

IULINUX_NAME="IULinux"
IULINUX_CHANNEL="development"

UBUNTU_SUITE="resolute"
TARGET_ARCH="amd64"
UBUNTU_MIRROR="http://archive.ubuntu.com/ubuntu"
UBUNTU_SECURITY_MIRROR="http://security.ubuntu.com/ubuntu"

IULINUX_VERSION="0.1-dev"
IULINUX_BASE_VERSION="26.04"
