---
efiSystemPartition: "/boot/efi"

enableLuksAutomatedPartitioning: false
drawNestedPartitions: true

userSwapChoices:
    - none
    - file

initialSwapChoice: file

defaultFileSystemType: "ext4"
availableFileSystemTypes:
    - "ext4"

partitionLayout:
    - name: "iulinux_root"
      filesystem: ext4
      mountPoint: "/"
      size: 100%
