---
dontChroot: false

script:
    - "rm -f /etc/sddm.conf.d/iulinux-live.conf"
    - "rm -f /usr/share/applications/iulinux-installer.desktop"
    - "rm -f /usr/bin/iulinux-installer"
    - "apt-get --purge -q -y remove calamares calamares-data libcalamares3.3 libcalamaresui3.3 casper squashfs-tools"
    - "rm -rf /etc/calamares"

i18n:
    name: "Finalizing IULinux installation"
